"""
Strategy Agent for Binance Futures Trading System.
Builds an ML ensemble (RandomForest, GradientBoosting, LogisticRegression)
to generate directional trading signals.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.exceptions import NotFittedError

from agents.market_analysis import MarketData

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by the strategy ensemble."""
    symbol: str
    direction: str          # 'LONG', 'SHORT', 'NEUTRAL'
    confidence: float       # 0.0 – 1.0
    rf_prob: float          # RandomForest probability of the predicted class
    gb_prob: float          # GradientBoosting probability
    lr_prob: float          # LogisticRegression probability
    ensemble_prob: float    # Weighted ensemble probability
    regime: str
    trend: str
    volatility: str
    features_used: List[str]
    timestamp: datetime
    is_valid: bool          # confidence >= threshold

    def to_dict(self) -> Dict[str, Any]:
        return {
            "symbol": self.symbol,
            "direction": self.direction,
            "confidence": self.confidence,
            "rf_prob": self.rf_prob,
            "gb_prob": self.gb_prob,
            "lr_prob": self.lr_prob,
            "ensemble_prob": self.ensemble_prob,
            "regime": self.regime,
            "trend": self.trend,
            "volatility": self.volatility,
            "created_at": self.timestamp.isoformat(),
        }


FEATURE_NAMES = [
    "rsi", "rsi_prev",
    "macd_hist", "macd_hist_prev",
    "bb_pct_b", "bb_width",
    "adx", "adx_pos", "adx_neg",
    "stoch_k", "stoch_d",
    "ema9_vs_ema21",
    "ema21_vs_ema50",
    "price_vs_ema50",
    "volume_ratio",
    "atr_pct",
    "cci",
    "williams_r",
    "returns_1", "returns_3", "returns_5",
    "volatility_5",
]


class StrategyAgent:
    """
    ML ensemble strategy agent that generates directional trading signals.

    Three models are trained on historical OHLCV+indicator data:
      - RandomForestClassifier   (weight 0.4)
      - GradientBoostingClassifier (weight 0.4)
      - LogisticRegression        (weight 0.2)

    The target is +1 (LONG) if price rises >0.5% in 3 candles,
    -1 (SHORT) if it falls >0.5%, else 0 (NEUTRAL).
    """

    RF_WEIGHT = 0.4
    GB_WEIGHT = 0.4
    LR_WEIGHT = 0.2

    def __init__(self, config=None):
        from config import TradingConfig
        self.config = config or TradingConfig()

        # Per-symbol model instances to avoid cross-contamination between symbols
        self._symbol_models: Dict[str, Dict] = {}
        self._is_trained: Dict[str, bool] = {}
        self._call_counts: Dict[str, int] = {}

    def _get_models(self, symbol: str) -> Dict:
        """Return (creating if needed) the model set for a given symbol."""
        if symbol not in self._symbol_models:
            self._symbol_models[symbol] = {
                "rf": RandomForestClassifier(
                    n_estimators=200, max_depth=8, min_samples_leaf=5,
                    random_state=42, n_jobs=-1, class_weight="balanced"
                ),
                "gb": GradientBoostingClassifier(
                    n_estimators=150, max_depth=4, learning_rate=0.05,
                    random_state=42, subsample=0.8
                ),
                "lr": LogisticRegression(
                    max_iter=1000, C=0.5, solver="lbfgs",
                    random_state=42
                ),
                "scaler": StandardScaler(),
            }
        return self._symbol_models[symbol]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_signal(self, market_data: MarketData) -> Signal:
        """
        Generate a trading signal from the latest MarketData.

        If the models haven't been trained yet (cold start), or if the
        retraining interval has been reached, retraining is attempted first.

        Returns a Signal dataclass.
        """
        symbol = market_data.symbol
        df = market_data.ohlcv

        self._call_counts[symbol] = self._call_counts.get(symbol, 0) + 1
        retrain_needed = (
            not self._is_trained.get(symbol, False)
            or self._call_counts[symbol] % self.config.retrain_interval == 0
        )

        if retrain_needed:
            trained = self._train(symbol, df)
            self._is_trained[symbol] = trained

        if not self._is_trained.get(symbol, False):
            logger.info("%s: Models not trained yet (cold start), returning NEUTRAL", symbol)
            return self._neutral_signal(market_data)

        return self._predict(market_data, df)

    # ------------------------------------------------------------------
    # Feature engineering
    # ------------------------------------------------------------------

    def _build_feature_matrix(self, df: pd.DataFrame) -> pd.DataFrame:
        """Build the feature DataFrame from the OHLCV+indicators DataFrame."""
        feat = pd.DataFrame(index=df.index)

        close = df["close"]

        feat["rsi"]       = df["rsi"]
        feat["rsi_prev"]  = df["rsi"].shift(1)

        feat["macd_hist"]      = df["macd_hist"]
        feat["macd_hist_prev"] = df["macd_hist"].shift(1)

        feat["bb_pct_b"]  = df["bb_pct_b"]
        feat["bb_width"]  = df["bb_width"]

        feat["adx"]       = df["adx"]
        feat["adx_pos"]   = df["adx_pos"]
        feat["adx_neg"]   = df["adx_neg"]

        feat["stoch_k"]   = df["stoch_k"]
        feat["stoch_d"]   = df["stoch_d"]

        # Relative EMA positions
        ema9  = df["ema9"]
        ema21 = df["ema21"]
        ema50 = df["ema50"]

        feat["ema9_vs_ema21"]   = (ema9  - ema21) / ema21.replace(0, np.nan)
        feat["ema21_vs_ema50"]  = (ema21 - ema50) / ema50.replace(0, np.nan)
        feat["price_vs_ema50"]  = (close - ema50) / ema50.replace(0, np.nan)

        feat["volume_ratio"] = df["volume_ratio"]
        feat["atr_pct"]      = df["atr"] / close.replace(0, np.nan)

        feat["cci"]         = df["cci"]
        feat["williams_r"]  = df["williams_r"]

        # Returns
        ret = close.pct_change()
        feat["returns_1"] = ret
        feat["returns_3"] = close.pct_change(3)
        feat["returns_5"] = close.pct_change(5)

        # Rolling volatility
        feat["volatility_5"] = ret.rolling(5).std()

        return feat

    def _build_target(self, df: pd.DataFrame, horizon: int = 3, threshold: float = 0.005) -> pd.Series:
        """
        Build classification target.
        +1 (LONG)  if future_close > close * (1 + threshold)
        -1 (SHORT) if future_close < close * (1 - threshold)
         0         otherwise
        """
        close = df["close"]
        future_close = close.shift(-horizon)
        ratio = future_close / close.replace(0, np.nan)

        target = pd.Series(0, index=df.index, dtype=int)
        target[ratio > (1 + threshold)] = 1
        target[ratio < (1 - threshold)] = -1
        return target

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def _train(self, symbol: str, df: pd.DataFrame) -> bool:
        """Train all three models for the given symbol. Returns True on success."""
        if len(df) < 100:
            logger.warning("%s: Not enough data to train (%d rows)", symbol, len(df))
            return False

        try:
            # Use up to last 1000 candles
            train_df = df.tail(1000).copy()

            feat_df = self._build_feature_matrix(train_df)
            target  = self._build_target(train_df)

            # Align and drop NaN
            combined = pd.concat([feat_df, target.rename("target")], axis=1)
            combined = combined.dropna()

            if len(combined) < 60:
                logger.warning("%s: Not enough clean rows to train (%d)", symbol, len(combined))
                return False

            X = combined[FEATURE_NAMES].values
            y = combined["target"].values

            # Ensure we have multiple classes
            unique_classes = np.unique(y)
            if len(unique_classes) < 2:
                logger.warning("%s: Only one class in training data, skipping", symbol)
                return False

            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=42, shuffle=False
            )

            models = self._get_models(symbol)
            scaler = models["scaler"]

            # Fit scaler on training data only
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled  = scaler.transform(X_test)

            # Train models
            models["rf"].fit(X_train, y_train)
            models["gb"].fit(X_train, y_train)
            models["lr"].fit(X_train_scaled, y_train)

            rf_score = models["rf"].score(X_test, y_test)
            gb_score = models["gb"].score(X_test, y_test)
            lr_score = models["lr"].score(X_test_scaled, y_test)

            logger.info(
                "%s: Models trained (n=%d) — RF=%.3f GB=%.3f LR=%.3f",
                symbol, len(X_train), rf_score, gb_score, lr_score,
            )
            return True

        except Exception as exc:
            logger.exception("%s: Training failed: %s", symbol, exc)
            return False

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------

    def _predict(self, market_data: MarketData, df: pd.DataFrame) -> Signal:
        """Run the ensemble on the latest feature row and return a Signal."""
        symbol = market_data.symbol
        try:
            feat_df = self._build_feature_matrix(df)
            last_features = feat_df.iloc[-1][FEATURE_NAMES]

            if last_features.isna().any():
                logger.warning("%s: NaN in features, returning NEUTRAL", symbol)
                return self._neutral_signal(market_data)

            X = last_features.values.reshape(1, -1)
            models = self._get_models(symbol)
            X_scaled = models["scaler"].transform(X)

            # Get class order — may be [-1, 0, 1] or subset
            rf_classes = list(models["rf"].classes_)
            gb_classes = list(models["gb"].classes_)
            lr_classes = list(models["lr"].classes_)

            rf_proba  = models["rf"].predict_proba(X)[0]
            gb_proba  = models["gb"].predict_proba(X)[0]
            lr_proba  = models["lr"].predict_proba(X_scaled)[0]

            # Map to standard [-1, 0, 1] probability dict
            rf_map = {cls: prob for cls, prob in zip(rf_classes, rf_proba)}
            gb_map = {cls: prob for cls, prob in zip(gb_classes, gb_proba)}
            lr_map = {cls: prob for cls, prob in zip(lr_classes, lr_proba)}

            def get_prob(prob_map, cls):
                return float(prob_map.get(cls, 0.0))

            # Weighted ensemble probabilities for each class
            long_prob  = (
                self.RF_WEIGHT * get_prob(rf_map, 1) +
                self.GB_WEIGHT * get_prob(gb_map, 1) +
                self.LR_WEIGHT * get_prob(lr_map, 1)
            )
            short_prob = (
                self.RF_WEIGHT * get_prob(rf_map, -1) +
                self.GB_WEIGHT * get_prob(gb_map, -1) +
                self.LR_WEIGHT * get_prob(lr_map, -1)
            )
            neutral_prob = (
                self.RF_WEIGHT * get_prob(rf_map, 0) +
                self.GB_WEIGHT * get_prob(gb_map, 0) +
                self.LR_WEIGHT * get_prob(lr_map, 0)
            )

            # Best direction
            if long_prob >= short_prob and long_prob >= neutral_prob:
                direction    = "LONG"
                ensemble_prob = long_prob
                rf_out       = get_prob(rf_map, 1)
                gb_out       = get_prob(gb_map, 1)
                lr_out       = get_prob(lr_map, 1)
            elif short_prob > long_prob and short_prob >= neutral_prob:
                direction    = "SHORT"
                ensemble_prob = short_prob
                rf_out       = get_prob(rf_map, -1)
                gb_out       = get_prob(gb_map, -1)
                lr_out       = get_prob(lr_map, -1)
            else:
                direction    = "NEUTRAL"
                ensemble_prob = neutral_prob
                rf_out       = get_prob(rf_map, 0)
                gb_out       = get_prob(gb_map, 0)
                lr_out       = get_prob(lr_map, 0)

            # Confidence is the ensemble probability for the chosen direction
            confidence = float(np.clip(ensemble_prob, 0.0, 1.0))
            is_valid = (direction != "NEUTRAL") and (confidence >= self.config.confidence_threshold)

            regime    = market_data.regime
            return Signal(
                symbol=symbol,
                direction=direction,
                confidence=confidence,
                rf_prob=round(float(rf_out), 4),
                gb_prob=round(float(gb_out), 4),
                lr_prob=round(float(lr_out), 4),
                ensemble_prob=round(float(ensemble_prob), 4),
                regime=regime.regime,
                trend=regime.trend,
                volatility=regime.volatility,
                features_used=FEATURE_NAMES,
                timestamp=datetime.now(timezone.utc),
                is_valid=is_valid,
            )

        except (NotFittedError, Exception) as exc:
            logger.exception("%s: Prediction failed: %s", symbol, exc)
            return self._neutral_signal(market_data)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _neutral_signal(self, market_data: MarketData) -> Signal:
        """Return a NEUTRAL signal with zero confidence."""
        regime = market_data.regime
        return Signal(
            symbol=market_data.symbol,
            direction="NEUTRAL",
            confidence=0.0,
            rf_prob=0.0,
            gb_prob=0.0,
            lr_prob=0.0,
            ensemble_prob=0.0,
            regime=regime.regime,
            trend=regime.trend,
            volatility=regime.volatility,
            features_used=FEATURE_NAMES,
            timestamp=datetime.now(timezone.utc),
            is_valid=False,
        )
